#+TITLE: Практическое занятие. Защита права собственности и иных вещных прав
#+startup: indent fold
#+options: author:nil date:nil toc:nil num:nil
#+language: ru

#+latex_compiler: xelatex
#+latex_header: \usepackage[a4paper,margin=2cm]{geometry}
#+latex_header: \usepackage{fontspec}
#+latex_header: \setmainfont{PT Astra Serif}
#+latex_header: \setsansfont{PT Astra Sans}
#+latex_header: \usepackage{indentfirst}
#+latex_header: \usepackage{enumitem}
#+latex_header: \setlist{nosep}
#+latex_header: \sloppy

* Основные вопросы
1. Гражданско-правовые способы защиты права собственности и иных вещных прав.
2. Истребование имущества из чужого незаконного владения (виндикационный иск) (ст. 301 ГК РФ). Особенности истребования имущества от добросовестного приобретателя: ограничение виндикации (ст. 302 ГК РФ). Расчеты при возврате имущества из незаконного владения (ст. 303 ГК РФ).
3. Защита права собственности от нарушений, не связанных с лишением владения (негаторный иск) (ст. 304 ГК РФ).
4. Иные вещно-правовые способы защиты (иск о признании вещного права, иск об освобождении имущества от ареста). Защита прав владельца, не являющегося собственником (ст. 305 ГК РФ).
* Источники
1) Постановление Конституционного Суда РФ от 21.04.2003 N 6-П «По делу о проверке конституционности положений пунктов 1 и 2 статьи 167 Гражданского кодекса Российской Федерации в связи с жалобами граждан О.М. Мариничевой, А.В. Немировской, З.А. Скляновой, Р.М. Скляновой и В.М. Ширяева»;
2) Постановление Пленума ВС РФ №10. Пленума ВАС РФ №22 от 29.04.2010 «О некоторых вопросах, возникающих в судебной практике при разрешении споров, связанных с защитой права собственности и других вещных прав»;
3) Информационное письмо Президиума ВАС РФ от 15.01.2013 № 153 «Обзор судебной практики по некоторым вопросам защиты прав собственника от нарушений, не связанных с лишением владения»;
4) Обзор судебной практики по делам, связанным с истребованием жилых помещений от добросовестных приобретателей, по искам государственных органов и органов местного самоуправления (утв. Президиумом Верховного Суда РФ 01.10.2014)
5) Обзор судебной практики по делам, связанным с истребованием жилых помещений от граждан по искам государственных органов и органов местного самоуправления (утв. Президиумом Верховного Суда РФ 25.11.2015)
* Задачи
** Задача 1
ОАО «Аграрник» предъявило к коммерческому банку (КБ) «Фонд» (ПАО) иск об истребовании здания. В обоснование своих требований истец ссылался на то, что в 2006 г. принадлежавшее ему здание  было  продано ОАО «Мой  город». Впоследствии в отношении здания было совершено три сделки. Последним покупателем являлся ответчик - КБ «Фонд». Истец представил суду доказательства, что он здание не продавал, на договоре подпись генерального директора подделана.

Банк не признал исковые  требования  и указал следующее. Здание он приобрел у организации, указанной  в качестве собственника в государственном реестре прав на недвижимое имущество. О предшествующих сделках с предметом спора он ничего не знал. Как добросовестный приобретатель он стал собственником здания, и в силу этого последнее не может быть у него истребовано. Кроме того, им проведены капитальный ремонт здания и переоборудование его помещений под банковский офис на общую сумму 8 млн. долларов США. Согласно заключению экспертизы в результате реконструкции создан совершенно новый объект нежилого фонда.

Арбитражный суд, признав банк добросовестным и возмездным приобретателем, тем не менее иск удовлетворил, сославшись на то, что здание выбыло из владения собственника (истца) помимо его воли.

Какие изложенные в задаче обстоятельства имеют значение для дела? Можно ли считать постановленное судом решение законным и обоснованным?
** Задача 2
Товарищество собственников жилья обратилось в арбитражный суд с иском к банку об истребовании из чужого незаконного владения помещения вестибюля, расположенного на первом этаже многоквартирного дома, и об обязании привести данное помещение в первоначальное состояние.

В обоснование своих исковых требований истец пояснил, что спорное помещение является вестибюлем многоквартирного дома, а потому относится к общему имуществу собственников многоквартирного дома. Банк самовольно занял данное помещение и безвозмездно использует в своих интересах в качестве офиса, установив в нем системы кондиционирования, видеонаблюдения, информационное табло, отражающее курсы валют, а также банкоматы, что в целом повлекло значительное ограничение доступа других лиц в спорное помещение. Вместе с тем решение общего собрания собственников многоквартирного дома о предоставлении спорного помещения в пользование банку не принималось.

Возражая против исковых требований, банк заявил, что является собственником нежилого помещения в многоквартирном доме, ввиду чего имеет право пользоваться общим имуществом многоквартирного дома без какого-либо разрешения других собственников. Кроме того, банк считает возможным и дальше использовать вестибюль и размещать в нем свое имущество, поскольку именно такой порядок пользования общим имуществом многоквартирного дома складывался на протяжении значительного периода времени.

Вопросы:

1. Назовите избранные истцом способы защиты гражданских прав.
2. Каким образом собственники помещений в многоквартирном доме владеют, пользуются и распоряжаются общим имуществом в многоквартирном доме?
3. Определите обстоятельства, имеющие значение для разрешения спора, а также доказательства, необходимые для обоснования позиций истца и ответчика.
4. Подлежат ли удовлетворению исковые требования товарищества собственников жилья?
** Задача 3
Между ООО «Мосгилевс» и ООО «Кирпич» был заключен договор поставки, по которому последнее общество обязалось поставить 10 000 шт. кирпича на строительную площадку по адресу: 3-я ул. Строителей 25. Однако в путевых листах была допущена ошибка, и груз был доставлен на строительную площадку ООО «ОмСтрой» по адресу 13-я ул. Строителей, д. 25.

Поскольку у ООО «Кирпич» отсутствовал другой аналогичный товар, ООО «Мосгилевс» обратилось к ООО «ОмСтрой» с просьбой вернуть кирпич, однако получило ответ, что в настоящий момент в связи с необходимостью строчного окончания работ по договору долевого участия в строительстве свободный строительный материал отсутствует.

ООО «Мосгилевс» обратилось в Арбитражный суд с виндикационным иском об истребовании 10 000 шт. кирпича из чужого незаконного владения ООО «ОмСтрой».

Какое решение вынесет суд?
** Задача 4
Цезарев, проживающий в г. Омске, узнал, что квартира в г. Екатеринбурге, которую он приобрел в надежде через некоторое время переехать, в результате мошеннических действий была переоформлена на Актавианова. Цезарев обратился в суд к Актавианову с виндикационным иском об истребовании квартиры из чужого незаконного владения. Актавианов возражал против удовлетворения иска, мотивировав тем, что виндикационный иск может быть удовлетворен только в отношении фактического владельца квартиры. В судебном заседании было установлено, что Актавианов передал квартиру по договору найма семье Клавдиевых, которые в ней и проживают по настоящее время. Поскольку Актавианов не является фактическим владельцем квартиры, то виндикационный иск не подлежит удовлетворению. Цезарев настаивал на иске к Актавианову, поскольку в ЕГРН значилась его фамилия.

Как должен поступить суд в данной ситуации?
** Задача 5
После смерти гражданки Пониной, к ее дочери – Зубилкиной М.М., перешло в порядке наследования движимое и недвижимое имущество, в том числе и дорогая импортная швейная машина фирмы Zinger, стоимость 150 тыс. рублей. Поскольку Зубилкина не была склонна к занятию швейным делом, она передала машинку в ссуду своей знакомой – Рубиной.  Спустя пол года она случайно узнала, что Рубина продала за 15 тыс. рублей швейную машинку Половинкиной, которая занимается швейным бизнесом.

Назовите гражданско-правовые способы защиты прав в данной ситуации? Какие требования и к кому могут быть предъявлены?
** Задача 6
Семенов, собственник индивидуального жилого, обнаружил, что на фундаменте дома появилась трещина. У него возникло подозрение, что она появилась вследствие проведения на соседнем земельном участке его соседом – Батоновым работ по строительству летней веранды в которой Ботонов вырыл погреб для хранения продуктов. Семенов потребовал от Батонова прекратить работы, так как они могут привести к разрушению его дома. Однако Батонов сказал, что не требуется получать в Администрации разрешение на устройство летней веранды и сооружение погреба, он осуществляет работы на своем земельном участке, и как собственник земельного участка волен делать все что захочет. 	Семенов обратился к сыну своего знакомого, студенту юридической академии, с просьбой защитить его права и законные интересы.

У студента юридической академии возник вопрос, каким иском защищать интересы Семенова в сложившейся ситуации, негаторным или деликтным? Обоснуйте свою точку зрения.
** Задача 7
Гришковец, собственник двухкомнатной квартиры, обнаружил в своем почтовом ящике письмо от службы судебных приставов с требованием добровольно исполнить решение районного суда города и освободить незаконно занимаемое жилое помещение. Когда он обратился в службу судебных приставов за разъяснением, ему сообщили, что по иску

Гришкова, который является собственником этой квартиры, суд и вынес такое решение. Если Гришковец не выселится в срок до 1 апреля, то службой судебных приставов будут осуществлены действия по принудительному выселению.

Гришковец обратился к знакомому юристу, который занимался сопровождением сделок с жилыми помещениями в риэлтерской организации «Сиеста», с просьбой помочь. Юрист узнал в Росреестре, что на самом деле, квартира зарегистрирована за Гришковым. Поскольку запись в ЕГРН нарушает права Гришковца, юрист предложил обратиться с виндикационным иском, так как в одном из постановлений высших судебных инстанций он читал, что для внесения новой записи в ЕГРП нужно, чтобы суд вынес решение по виндикационному иску.

В судебном заседании Гришков заявил, что Гришковец пропустил срок исковой давности, так как он приобрел квартиру 3,5 года назад, и с тех пор на квитанциях управляющей компании значится его фамилия. Какое решение вынесет суд?
* Задание
Найти два судебных дела, в одном из которых заявлен виндикационный иск, а в другом – негаторный, кратко описать его фабулу и подготовить проекты исковых заявлений по двум отобранным делам.
