#+startup: indent fold

#+options: author:nil date:nil toc:nil num:nil
#+title: Общая собственность

* Вопросы
1. Понятие и виды права общей собственности.
2. Основания возникновения права общей собственности.
3. Раскройте особенности владения, пользования и распоряжения имуществом, находящемся в общей долевой собственности.

* Задачи
** Задача 1
Ярополк, Велимудр и Миролюб учредили крестьянское (фермерское) хозяйство «Серп» для осуществления фермерской деятельности, о чем в ЕГРЮЛ внесена соответствующая запись. Ярополк в качестве вклада внес принадлежащий ему земельный участок, Велимудр — денежные средства, трактор серии 4WD, сельскохозяйственный инвентарь, а Миролюб — принадлежащий ему склад готовой продукции.

В связи с тем, что крестьянское (фермерское) хозяйство постоянно испытывало финансовые трудности, Велимудр решил прекратить фермерскую деятельность и потребовал раздела совместного имущества, возврата принадлежавшего ему трактора и выдела земельного участка.

Вопросы:

1. Что такое крестьянское фермерское хозяйство (КФХ)?
2. Что является общим имуществом членов КФХ?
3. Каким образом осуществляется распоряжение имуществом КФХ?
4. Подлежит ли разделу имущество КФХ при выходе из него одного из членов?
5. Имеет ли право гражданин на компенсацию в случае выхода из КФХ?
6. Что происходит с имуществом КФХ при выходе из него всех членов?
7. Определите нормы, подлежащие применению к спорным правоотношениям.
8. Подлежат ли удовлетворению требования Велимудра и в каком порядке?
** Задача 2
Глава крестьянского (фермерского) хозяйства обратился в департамент имущественных отношений субъекта РФ с заявлением о приобретении в собственность находящегося у него в аренде земельного участка из земель сельскохозяйственного назначения. Департамент имущественных отношений субъекта РФ отказал заявителю в предоставлении в собственность данного земельного участка. Причиной тому послужило отсутствие нотариально удостоверенного согласия супруги заявителя на совершение сделки по приобретению земельного участка, необходимость предоставления которого предусмотрена Административным регламентом предоставления государственной услуги по предоставлению в собственность за плату земельных участков из земель сельскохозяйственного назначения на территории субъекта РФ, находящихся в государственной собственности, утвержденным приказом департамента имущественных отношений субъекта РФ. Глава крестьянского (фермерского) хозяйства обратился в арбитражный суд с заявлением к департаменту имущественных отношений субъекта РФ о признании данного отказа незаконным, а также возложении на департамент обязанности принять решение о предоставлении в собственность заявителя спорного земельного участка. Решением суда в удовлетворении требований главы крестьянского (фермерского) хозяйства отказано, поскольку предоставление нотариально удостоверенного согласия супруга на совершение сделки в силу положений административного регламента, то есть действующего нормативного правового акта субъекта РФ, является обязательным для получения заинтересованным лицом соответствующей государственной услуги.

Вопросы:

1. Вспомните содержание понятия «гражданское законодательство». Являются ли нормативные правовые акты субъектов РФ источниками гражданского права?
2. Какие нормативные правовые акты содержат правила о владении, пользовании и распоряжении общим имуществом супругов? Назовите особенности владения, пользования и распоряжения общим имуществом супругов.
3. Вправе ли суд при рассмотрении споров, связанных с защитой гражданских прав, не применять противоречащий закону акт государственного органа или органа местного самоуправления независимо от признания этого акта недействительным?
4. Дайте оценку выводам суда. Рассмотрите заявленные требования и решите дело.
