#+startup: indent fold

#+options: author:nil date:nil toc:nil num:nil
#+title: Приобретение и прекращение права собственности

* Задания
** Задание 1
Под первоначальными способами возникновения права собственности понимаются способы, при которых право собственности на вещь:

а) возникает впервые либо помимо прав и воли предшествующего собственника;

б) возникает в силу прямого указания закона;

в) возникает при производстве новой вещи.
** Задание 2
Под производными способами возникновения права собственности понимают способы, при которых право собственности на вещь:

а) основано на праве предшествующего собственника;

б) не зависит от права предшествующего собственника на данную вещь;

в) обусловливает появление права «следования» на вещь.
** Задание 3
В таблице отразите систему первоначальных и производных способов приобретения права собственности. Сделайте вывод об основных отличиях между ними.
** Задание 4
Какие основания (способы) возникновения права собственности присущи только государству?

а) реквизиция, конфискация, национализация, приобретательная давность;

б) реквизиция, конфискация, правопреемство при реорганизации юридического лица;

в) реквизиция, конфискация, национализация;

г) конфискация, национализация, правопреемство при реорганизации юридического лица, приобретательная давность.
** Задание 5
Руководствуясь постановлением Пленумов ВС РФ и ВАС РФ от 29 апреля 2010 г. № 10/22 «О некоторых вопросах, возникающих в судебной практике при разрешении споров, связанных с защитой права собственности и других вещных прав», разъясните применение норм ГК по следующим вопросам:

- как определяется момент возникновения права собственности граждан и юридических лиц на имущество, созданное ими для себя;
- как определяется момент возникновения права собственности граждан и юридических лиц на имущество, приобретенное от других лиц на основании сделок об отчуждении этого имущества.
** Задание 6
Заполните таблицу.

| Критерий                                     | Реквизиция | Конфискация | Национализация |
|----------------------------------------------+------------+-------------+----------------|
| Понятие                                      |            |             |                |
| Нормативная основа                           |            |             |                |
| Принудительный или добровольный характер     |            |             |                |
| Возмездный или безвозмездный характер        |            |             |                |
| Цель применения                              |            |             |                |
| Условия применения                           |            |             |                |
| Судебный или внесудебный характер применения |            |             |                |

* Задачи
** Задача 1
В 2012 г. на дачном участке в черте г. Пенза без каких-либо разрешений был построен трехэтажный жилой дом. Собственник участка, Маковкин заключил с Коробейниковым договор купли-продажи 1/2 доли дома. Оборудовав дом раздельными изолированными санитарными узлами и выходами, они стали пользоваться домом сообща на две семьи. Администрация города обратилась в суд с иском о сносе самовольной постройки, поскольку строительство дома производилось без получения разрешений, кроме того собственники дома самовольно подключили дом к городской электросети.

Когда возникает право собственности на дом? Является ли в данном случае позиция органа местного самоуправления обоснованной? Можно ли признать самовольной постройкой данный дом? Какой способ защиты прав на энергоресурсы будет правильным?
** Задача 2
Комната Огородниковой находится в средней части дома, примыкая с обеих сторон к комнатам других собственников. Огородникова не пользовалась ею, не отапливала и не ремонтировала в течение 10 лет, в результате чего та пришла в непригодное для проживания состояние, что создавало неблагоприятные условия для пользования домом другими собственниками. Как-то через разбитые окна в комнату проникли подростки, разожгли в ней костер и чуть не устроили пожар. Соседи обратились к администрации района с просьбой принять необходимые меры. Администрация вынесла решение о безвозмездном изъятии у Огородниковой принадлежащей ей части дома как бесхозяйственно содержимой.

Правомерно ли это решение?
** Задача 3
Кооператив «Сервис» взял в аренду дом. Во время капитального ремонта здания при разборке внутренней стены были обнаружены серебряные и золотые монеты, украшения, часы в золотой оправе, серебряная кухонная утварь. Известно, что дом раньше принадлежал купцу. Председатель кооператива считает, что все вещи нужно сдать государству.

Кому принадлежат найденные предметы? Подлежит ли выплате вознаграждение и если да, то кому?
** Задача 4
В газете «Вечерний Омск» помещено объявление: «Потерялась собака по кличке Лана, рыже-белой масти, сиба-ину, возраст 8 месяцев, на ошейнике выбито имя. Нашедшему гарантируется вознаграждение. Обращаться по адресу: Восточная, д. 25». Через неделю Ступин привел собаку по указанному адресу и потребовал кроме вознаграждения оплаты расходов на ее питание в сумме 150 руб.

Подлежит ли его требование удовлетворению?
** Задача 5
В квартиру Ванниковой для производства обыска и выемки явился работник милиции. При осмотре квартиры он увидел закрепленные на стене пистолеты, револьверы, охотничьи ружья, кинжалы, которые были размещены в определенном порядке и представляли собой коллекцию. Ванникова пояснила, что все это ей досталось по наследству от деда и отца, никаких патронов к огнестрельному оружию нет. Некоторое оружие имело дарственные надписи. Из документов, оставшихся от отца Ванниковой, было ясно, что все указанные предметы находятся в законном владении хозяйки. Работник милиции составил акт о незаконном хранении оружия.

Имеются ли основания для изъятия указанного оружия?
** Задача 6
Левандовский жил в собственном доме. В связи с ухудшением состояния здоровья он решил по совету врача на 2 года уехать к сыну в другой город, а дом по договору аренды сдал Сальникову. Арендную плату тот должен был отсылать переводом. По истечении 2 лет Левандовский не вернулся, но Сальников продолжал пересылать ему арендную плату. Через год перевод Сальникову был возвращен за истечением срока хранения. Он продолжал жить в доме, сделал капитальный ремонт, вносил все необходимые платежи за него как за свой собственный.

Спустя 7 лет Сальников умер, в доме остались его жена и совершеннолетний сын с семьей. Еще через 6 лет в город приехал внук Левандовского и потребовал освободить дом, так как он желает его продать. Сальников-младший считает, что дом принадлежит ему на праве собственности.

Составьте исковое заявление от имени Сальникова. Каким, на Ваш взгляд, будет решение суда?
** Задача 7
Член ЖСК Журавлев полностью выплатил паевой взнос за квартиру. В связи с выездом на постоянное жительство за границу он решил ее продать, но правление кооператива отказалось выдать ему справку о принадлежности квартиры: согласно уставу ЖСК кооператив является собственником дома, поэтому право продажи квартиры принадлежит только ему. Он согласен выплатить Журавлеву вырученную от продажи квартиры сумму.

Законны ли действия кооператива? Какие документы нужны Журавлеву для предъявления иска? Составьте проект искового заявления.
** Задача 8
Комитет по управлению городским имуществом обратился в арбитражный суд с иском к унитарному предприятию о выселении из нежилого помещения в связи с его изъятием. В судебном заседании было установлено, что помещение используется предприятием на основе устава, право хозяйственного ведения на него было передано ему городом в лице комитета по управлению имуществом при создании.

Имеется ли возможность изъятия имущества, находящегося у унитарного предприятия на праве хозяйственного ведения?
