title: Гражданское право

# description: Для студентов ОмЮК

lang: ru_RU

show_downloads: false

google_analytics: true

theme: jekyll-theme-tactile

github:
  is_project_page: false

collections:
  grpr:
    output: true
  spr:
    output: true
  presentations:
    output: true
  notifs:
    output: false
  info:
    output: true

defaults:
  - scope:
      path: ""
      type: "grpr"
    values:
      author: "Цыганова А.А. &mdash; Омский Юридический Колледж"
      layout: "page"
