---
title: Понятие гражданского права
author: Цыганова А.А. -- Омский Юридический Колледж
when: 12.06.2020
output:
  ioslides_presentation:
    wide: true
    smaller: true
    transition: faster
    mathjax: null
    self_contained: true
---

<style>
p {
  text-align: justify;
}
</style>

# Предмет гражданского права

## Предмет гражданского права

В **предмет гражданского права** согласно ст. 2 ГК включаются две группы
общественных отношений: во-первых, имущественные отношения рынка и, во-вторых,
неимущественные отношения, которые также обслуживают рынок, но прежде всего
защищают личные интересы, права и свободы граждан.

## Имущественные отношения

Общественные отношения, возникающие в связи с использованием различных
имущественных благ (природных ресурсов, вещей, работ, услуг, денежных средств и
др.), то есть это прежде всего рыночные отношения.

## Неимущественные отношения

Общим объектом личных неимущественных отношений являются нематериальные блага,
характеризующиеся отсутствием экономического содержания. К ним относятся честь,
достоинство, деловая репутация и т.п. Они неотчуждаемы и не могут переходить по
наследству.

# Спасибо за внимание
